// Blasted.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <thread>//for wait
#include <chrono>//for wait
#include <conio.h>//for key detection
#include <string>//for directory choice
#include <fstream>//for text files
using namespace std;

int main() {
		int rep = 0;
		while (rep < 5) {
			cout << "Connecting...\n";
			rep = rep + 1;
			this_thread::sleep_for(std::chrono::milliseconds(1500));
		}//repeats "connecting" 5 times



		cout << "Error connecting to Houston network. Trying backup...\n";
		rep = 0;
		this_thread::sleep_for(std::chrono::milliseconds(1500));//prints first message, and resets repeat counter variable, and pauses code for 1500 ms.



		while (rep < 5) {
			cout << "Connecting...\n";
			rep = rep + 1;
			this_thread::sleep_for(std::chrono::milliseconds(1500));
		}//repeats connecting another 5 times




		cout << "Backup network connection failed. Switching to radio mode...";
		this_thread::sleep_for(std::chrono::milliseconds(1000));
		cout << "Done.\n\n";
		this_thread::sleep_for(std::chrono::milliseconds(1000));//displays message of switching to radio mode.




		cout << "   *******      *         *****      *******      *******      *******      *******\n";
		cout << "   *      *     *        *     *    *                *         *            *      *\n";
		cout << "   *      *     *        *     *    *                *         *            *      *\n";
		cout << "   *******      *        *******     *******         *         *******      *      *\n";
		cout << "   *      *     *        *     *            *        *         *            *      *\n";
		cout << "   *      *     *        *     *            *        *         *            *      *\n";
		cout << "   *******      *******  *     *     *******         *         *******      *******\n\n";
		this_thread::sleep_for(std::chrono::milliseconds(1000));//displays logo, and waits 1000 ms.

		cout << "A SHORT TEXT BASED HORROR BY JACK TRUSCOTT\n\n"; //displays subtitle




		cout << "PRESS ENTER TO BEGIN, OR ESC TO QUIT\n";
		while (true) {
			if (_kbhit()) {  // Check if a key has been pressed
				char ch = _getch();  // Get the pressed key
	
				// Exit if the 'Esc' key is pressed
				if (ch == 27) {  // 27 is the ASCII value for the Escape key
					cout << "Exiting...\n";
					return 0;  // Exit the program
				}
	
				// If Enter is pressed, break the loop and start loading
				if (ch == 13) {  // 13 is the ASCII value for the Enter key
					cout << "Loading...\n";
					break;  // Break out of the loop
				}

				else {}
			}

		}//This segment was generated by AI, however I kinda know what it does. Checks for enter keystroke or escape keystroke, and closes game/continues running code depenging on ascii value.



		string name;
		string pass;

		cout << "LOGIN:\n\nUSERNAME\n\n";
		cin >> name;

		cout << "PASSWORD\n\n";

		cin >> pass; //accepts user and password, used for later gameplay

		cout << "Loading user data...";
		this_thread::sleep_for(std::chrono::milliseconds(1500));
		cout << "Done.\n";
		this_thread::sleep_for(std::chrono::milliseconds(1500));
		cout << "c";
		this_thread::sleep_for(std::chrono::milliseconds(250));
		cout << "d \\home\\";
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << name;
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << "\\docum";
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << "ents\\";
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << "log";
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << "s\\203";
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << "4\\apr";
		this_thread::sleep_for(std::chrono::milliseconds(150));
		cout << "il\\\n";
		this_thread::sleep_for(std::chrono::milliseconds(1000));
		cout << "l";
		this_thread::sleep_for(std::chrono::milliseconds(250));
		cout << "s\n"; 
		this_thread::sleep_for(std::chrono::milliseconds(1500)); 
		cout << "\\home\\" << name << "\\documents\\logs\\2034\\april\\\n";
		this_thread::sleep_for(std::chrono::milliseconds(200));
		cout << "1.txt	2.txt	3.txt	4.txt	5.txt	6.txt	7.txt\n\n\n\n";//plays animation for loading user's directory for when the game takes place, over a seven day period.



		string file;
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely.The static lingers longer than it should, and we sit in silence, waiting for any response.But there's nothing. We can still hear each other in the station, but no word from ground control. A strange unease settles over us. We've been trained for emergencies, but this doesn't feel like one.Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities lighting up like fireworks in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static. It's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Homesteaders, likely still operating their makeshift stations in the midst of the devastation. I immediately responded, using our station callsign:(TRANSCRIPT BELOW)\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy ? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with Kilo Foxtrot 3-9-8 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. \nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nKilo Foxtrot 3-9-8, the sky is dark with smoke. The cities... they've fallen. There's nothing left but ashes. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nWe're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again... it keeps something alive inside. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely.The static lingers longer than it should, and we sit in silence, waiting for any response.But there's nothing. We can still hear each other in the station, but no word from ground control. A strange unease settles over us. We've been trained for emergencies, but this doesn't feel like one.Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities lighting up like fireworks in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static. It's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Homesteaders, likely still operating their makeshift stations in the midst of the devastation. I immediately responded, using our station callsign:(TRANSCRIPT BELOW)\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy ? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with Kilo Foxtrot 3-9-8 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. \nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nKilo Foxtrot 3-9-8, the sky is dark with smoke. The cities... they've fallen. There's nothing left but ashes. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nWe're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again... it keeps something alive inside. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely.The static lingers longer than it should, and we sit in silence, waiting for any response.But there's nothing. We can still hear each other in the station, but no word from ground control. A strange unease settles over us. We've been trained for emergencies, but this doesn't feel like one.Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities lighting up like fireworks in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static. It's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Homesteaders, likely still operating their makeshift stations in the midst of the devastation. I immediately responded, using our station callsign:(TRANSCRIPT BELOW)\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy ? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with Kilo Foxtrot 3-9-8 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. \nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nKilo Foxtrot 3-9-8, the sky is dark with smoke. The cities... they've fallen. There's nothing left but ashes. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nWe're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again... it keeps something alive inside. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely.The static lingers longer than it should, and we sit in silence, waiting for any response.But there's nothing. We can still hear each other in the station, but no word from ground control. A strange unease settles over us. We've been trained for emergencies, but this doesn't feel like one.Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities lighting up like fireworks in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static. It's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Homesteaders, likely still operating their makeshift stations in the midst of the devastation. I immediately responded, using our station callsign:(TRANSCRIPT BELOW)\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy ? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with Kilo Foxtrot 3-9-8 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. \nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nKilo Foxtrot 3-9-8, the sky is dark with smoke. The cities... they've fallen. There's nothing left but ashes. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nWe're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again... it keeps something alive inside. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely.The static lingers longer than it should, and we sit in silence, waiting for any response.But there's nothing. We can still hear each other in the station, but no word from ground control. A strange unease settles over us. We've been trained for emergencies, but this doesn't feel like one.Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities lighting up like fireworks in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static. It's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Homesteaders, likely still operating their makeshift stations in the midst of the devastation. I immediately responded, using our station callsign:(TRANSCRIPT BELOW)\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy ? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with Kilo Foxtrot 3-9-8 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. \nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nKilo Foxtrot 3-9-8, the sky is dark with smoke. The cities... they've fallen. There's nothing left but ashes. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nWe're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again... it keeps something alive inside. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely.The static lingers longer than it should, and we sit in silence, waiting for any response.But there's nothing. We can still hear each other in the station, but no word from ground control. A strange unease settles over us. We've been trained for emergencies, but this doesn't feel like one.Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities lighting up like fireworks in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static. It's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Homesteaders, likely still operating their makeshift stations in the midst of the devastation. I immediately responded, using our station callsign:(TRANSCRIPT BELOW)\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy ? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with Kilo Foxtrot 3-9-8 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. \nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nKilo Foxtrot 3-9-8, the sky is dark with smoke. The cities... they've fallen. There's nothing left but ashes. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nWe're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again... it keeps something alive inside. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}
		cin >> file;
		while (true) {
			if (file.find("1.txt") != string::npos) {
				ofstream outFile("1.txt");
				outFile << "Personal log 04/01/2034\nWe've started the slow process of decommissioning the ISS today, following the usual protocols. The station is old - 36 years in orbit and barely holding together. It's routine. Powering down the science labs, clearing out the old research equipment, shutting off communication relays. The systems are dated, some on their last legs, but we've kept them operational longer than anyone thought possible. Now, it's just about making sure everything is safely powered off, secured, and ready for the eventual re-entry. The Earth below is as stunning as ever, rotating peacefully in the distance. There's talk of rising tensions among the major powers back home, but we have our work cut out for us. The last thing we expect is for the decommissioning to be anything but routine." << endl;
				system("notepad.exe 1.txt");
				break;
			}
			else if (file.find("2.txt") != string::npos) {
				ofstream outFile("2.txt");
				outFile << "Personal log 04/02/2034\nToday's task was to power down the life support systems. It's a delicate process - closing down the oxygen generators and thermal regulation, making sure there are no leaks. The same checks we've done a thousand times. But as I reach for the switch, the comms crackle unexpectedly. At first, it's just static - fragments of voices breaking through the noise. We're used to occasional glitches, but this feels different. Then the transmission cuts out entirely. The static lingers longer than it should, and we sit in silence, waiting for any response. But there's nothing. We can still hear each other in the station, but no word from ground control. A strange sense of unease settles over us. We've been trained for emergencies, but this doesn't feel like one. Something is off." << endl;
				system("notepad.exe 2.txt");
				break;
			}
			else if (file.find("3.txt") != string::npos) {
				ofstream outFile("3.txt");
				outFile << "Personal log 04/03/2034\nThe station hums around us, but the stillness has settled into something far worse than quiet. It's as if the world below has stopped entirely. I check the comms again, trying to re-establish contact with Houston, but there's no response. And then—just as we begin to focus on what to do next - a bright flash erupts on the surface of the Earth. At first, it looks like a distant thunderstorm, but it's too intense, too sudden. I freeze. The flash is followed by another, then another. Cities are lighting up all over, dotting the ground like some kind of messed up firework show in the night. Only this isn't a celebration. It's something much worse. I don’t know what's happening down there, but the flashes seem too consistent, too deliberate." << endl;
				system("notepad.exe 3.txt");
				break;
			}
			else if (file.find("4.txt") != string::npos) {
				ofstream outFile("4.txt");
				outFile << "Personal log 04/04/2034\nThe flashes continue all night, and the world below seems to be burning with them. I try again to get any kind of communication, but the system is dead. The radio waves are filled with nothing but static, likely to the massive amounts of smoke and debris now visible from up here. We were supposed to have reduancy for issues like these, but it's as if we're disconnected entirely from Earth. My heart is racing as I watch the blinding light of explosions flicker across the planet's surface, lighting up entire regions in the blink of an eye. One of my colleagues suggests we send a distress signal, but without comms, that's impossible. We've been trained for these moments, but there's no protocol for a situation like this - where the world has erupted in flames, and we're floating in the silence of space, unable to reach anyone. The Earth we've known is slipping away. And we're still here, helpless." << endl;
				system("notepad.exe 4.txt");
				break;
			}
			else if (file.find("5.txt") != string::npos) {
				ofstream outFile("5.txt");
				outFile << "Personal log 04/05/2034\nI'm working on the backup communication systems now. It's a long shot, given all the smoke, but maybe we can get a signal through. I've gone through the manual twice already, checking every connection, every wire, every protocol, but nothing seems to work. It's like the system has been completely fried. It could well be, given that explosions of that magnitude put off an electromagnetic pulse. For all we know, our equipment could only think it works, while not getting a single signal through. Meanwhile, the flashes continue below, relentless. I can't look away. There's a sinking feeling in my chest as I watch the world I once knew being wiped out, piece by piece. The blasts are too bright, too frequent to be random. This isn’t just a war - it's something much larger, much worse than any conflict we've ever known. And we are stuck here, out of reach." << endl;
				system("notepad.exe 5.txt");
				break;
			}
			else if (file.find("6.txt") != string::npos) {
				ofstream outFile("6.txt");
				outFile << "Personal log 04/06/2034\nThe Earth below is shrouded in a chaotic storm of fire and smoke. Satellite and radio communications went down 4 days ago, and with it, our contact with Earth’s space agencies - Houston, Moscow, Beijing - all gone. That's assuming someone hasn't blown their centres to bits yet. The silence is deafening. I've been monitoring frequencies all night using the ham radio, desperate for any sign of life. Then - finally - amidst the static, I heard a faint voice. It was scrambled at first, but I caught the call sign: 'Kilo Foxtrot 3-9-8'. Ameture radio operators, somehow still operating their HAM radio stations in the midst of the devastation. I immediately responded, desperate for some form of communication. (TRANSCRIPT BELOW)\n\nISS: NA1SS to Kilo Foxtrot 3 - 9 - 8, do you copy? This is NA1SS, we are still in orbit.\n //The transmission was broken, filled with bursts of interference, but I could make out their reply.\nKF398: NA1SS, we hear you! We're here. Holding. How's the sky?\n //I don't know how long their survival will last, but for now, they remain. It's our last connection to the world below." << endl;
				system("notepad.exe 6.txt");
				break;
			}
			else if (file.find("7.txt") != string::npos) {
				ofstream outFile("7.txt");
				outFile << "Personal log 04/07/2034\nThis morning's transmission was more stable than last night's. I managed to make contact with KF398 again. The signal was weak, but there was clarity in their words. They spoke of rationing, keeping the small community together, and using the ham radio as their lifeline. They asked about the Earth, about the ISS, about what was left. (TRANSCRIPT BELOW)\n\nKF398: NA1SS, what's left of the world down there? What's happening?\n //I took a deep breath before responding, knowing the truth would hurt. \nISS:Kilo Foxtrot 3-9-8, the sky is dark with smoke. The cities, they've fallen. There's nothing left but ashes, and we can't see any lights until the smoke clears. But you're still there. You're holding.\n //There was a pause, long enough for me to worry if the signal had dropped again. Then their voice crackled through the static once more, tinged with both relief and sorrow: \nKF398: We're still here. We'll keep holding. You're our last link.\n //The isolation is overwhelming, but hearing their voices again, it keeps something alive inside us. As long as we're still in touch, there's a glimmer of hope. For now, at least, we keep the signal open." << endl;
				system("notepad.exe 7.txt");
				break;
			}
			else {
				cout << "Could not find the file specified.\n";
				cin >> file;
			}
		}






}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
